config/routes.rb
Rails.application.routes.draw do


  # GET -> list_products_path -> list_products_controller#index 
  # GET -> list_product_path -> list_products_controller#show -> :id
  # POST -> create_list_product_path -> list_products_controller#create -> product_id
  resources :list_products
  #add_to_list -> Post -> cree un nuevo ListProduct(user: current_user, product: product, carshopping: current_user.car_shopping)
 
  #list_products/add_to_list
  #mi_url_path
  #sin as: href="localhost:3000/list_products/add-to-list?product_id=1"
  #con as: add_to_list_path(product_id: @product.id)
  #to: controlador#metodo_del_controlador
  post "/add-to-list", to: "list_products#add_to_list", controller: "list_products", as: :add_to_list
  
  delete "/remove-from-cart/:id", to: "list_products#remove_from_cart", as: :remove_from_cart

  post "/shop_from_cart/", to: "list_products#shop_from_cart", as: :shop_from_cart
  
  
  #user_profile_path
  #link_to 'Mi perfil', 
  #views/users/profile.html.erb
  #get "/mi-perfil", to: "users#profile", controller: "users", as: :user_profile



  resources :editorials
  devise_for :users
  root to: "products#index"


  
  resources :carshoppings
  resources :whishlists
  resources :addres
  resources :shopingcars
  resources :whislists
  resources :products
  resources :categories
  resources :roles

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/carshopping.rb
# == Schema Information
#
# Table name: carshoppings
#
#  id         :bigint           not null, primary key
#  total      :integer          default(0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

=begin


=end
class Carshopping < ApplicationRecord
  belongs_to :user

  has_many :list_products

  #@carshopping.products = [producto1, producto2]
  has_many :products, through: :list_products

  # list_product_id  user_id product_id carshopping_id
  #   1                 1      1(name: batman)           2
  #   1                 1      2           2

  #carshopping.last.user

  #metodo para actualizar el total

  def actualizar_total(precio)
    #total anterior
    #cuanto se va a sumar (product.price)
    nuevo_total = self.total + precio

    puts "-------"
    puts nuevo_total
    puts "-------"
    self.update(total: nuevo_total)
  end
end

app/controllers/carshoppings_controller.rb
class CarshoppingsController < ApplicationController
  before_action :set_carshopping, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[index create]

  # GET /carshoppings or /carshoppings.json
  def index
    if current_user.carshopping.nil?
      # Construye un nuevo carshopping asociado al usuario actual
      @carshopping = current_user.build_carshopping(total: 0)
      respond_to do |format|
        if @carshopping.save
          format.html { redirect_to @carshopping, notice: "Carrito creado correctamente." }
          format.json { render :show, status: :created, location: @carshopping }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @carshopping.errors, status: :unprocessable_entity }
        end
      end
    else
      # Si ya existe, redirige directamente al carrito
      redirect_to current_user.carshopping
    end
  end
  
  # GET /carshoppings/1 or /carshoppings/1.json
  def show
    #@carshopping

    #desde el modelo que esta en la tabla auxiliar jalar los datos de los otros modelos de la misma tabla auxiliar
    @products = @carshopping.products
  end

  # GET /carshoppings/new
  def new
    @carshopping = Carshopping.new
    # Buscamos o inicializamos un carrito para el usuario actual

    @carshopping = Carshopping.find_or_initialize_by(user_id: current_user.id)

    if @carshopping.new_record?
      @carshopping.total = 0 
      if @carshopping.save
        redirect_to @carshopping, notice: "Carrito creado exitosamente."
      else
        redirect_to carshoppings_path, alert: "Hubo un problema al crear el carrito."
      end
    else
      
      redirect_to @carshopping
    end

  end

  # GET /carshoppings/1/edit
  def edit
  end

  # POST /carshoppings or /carshoppings.json
  def create

    #Carshopping(user: current_user)
    @carshopping = current_user.carshopping.new(carshopping_params)

    respond_to do |format|
      if @carshopping.save
        format.html { redirect_to @carshopping, notice: "Carrito creado correctamente." }
        format.json { render :show, status: :created, location: @carshopping }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carshopping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carshoppings/1 or /carshoppings/1.json
  def update
    respond_to do |format|
      if @carshopping.update(carshopping_params)
        format.html { redirect_to @carshopping, notice: "Carrito actualizado correctamente." }
        format.json { render :show, status: :ok, location: @carshopping }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carshopping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carshoppings/1 or /carshoppings/1.json
  def destroy
    @carshopping.destroy

    respond_to do |format|
      format.html { redirect_to carshoppings_path, notice: "Carrito eliminado correctamente." }
      format.json { head :no_content }
    end
  end

  private
    
    def set_carshopping
      @carshopping = Carshopping.find_by(id: params[:id])
      unless @carshopping
        redirect_to carshoppings_path, alert: 'Carrito no encontrado.'
      end
    end

    # Solo permitir parámetros confiables para la creación o actualización de un carrito
    def carshopping_params
      params.require(:carshopping).permit(:total)
    end
end

app/helpers/carshoppings_helper.rb
module CarshoppingsHelper
end

app/views/carshoppings/_carshopping.html.erb
<div id="<%= dom_id(@carshopping) %>" class="space-y-6">
  <p>
    <strong>Total:</strong>
    <%= @carshopping.total %>
  </p>

  <p>
    <strong>User:</strong>
    <%= current_user.email %>
  </p>
  <%= button_to 'Comprar', shop_from_cart_path, method: :post, class: 'btn btn-primary mt-2 bg-red-500 text-white py-1 px-4 rounded hover:bg-red-600' %>
       

  <h3 class="text-2xl font-semibold">Productos en el Carrito:</h3>

  <div class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-6">
    <% @carshopping.list_products.each do |list_product| %>
      <% product = list_product.product %>
        <div class="p-4">
          <h4 class="text-md font-semibold text-gray-800 truncate"><%= product.name %></h4>
          <p class="text-sm text-gray-600"><%= number_to_currency(product.price) %></p>
          <%= button_to 'Eliminar', remove_from_cart_path(list_product), method: :delete, class: 'btn btn-primary mt-2 bg-red-500 text-white py-1 px-4 rounded hover:bg-red-600' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/carshoppings/_form.html.erb
<%= form_with(model: carshopping) do |form| %>
  <% if carshopping.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(carshopping.errors.count, "error") %> prohibited this carshopping from being saved:</h2>

      <ul>
        <% carshopping.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.number_field :total %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/carshoppings/edit.html.erb
<h1>Editing carshopping</h1>

<%= render "form", carshopping: @carshopping %>

<br>

<div>
  <%= link_to "Show this carshopping", @carshopping %> |
  <%= link_to "Back to carshoppings", carshoppings_path %>
</div>

app/views/carshoppings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Carshoppings</h1>

app/views/carshoppings/new.html.erb
<h1>New carshopping</h1>

<%= render "form", carshopping: @carshopping %>

<br>

<div>
  <%= link_to "Back to carshoppings", carshoppings_path %>
</div>

app/views/carshoppings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @carshopping %>