config/routes.rb
Rails.application.routes.draw do


  # GET -> list_products_path -> list_products_controller#index 
  # GET -> list_product_path -> list_products_controller#show -> :id
  # POST -> create_list_product_path -> list_products_controller#create -> product_id
  resources :list_products
  #add_to_list -> Post -> cree un nuevo ListProduct(user: current_user, product: product, carshopping: current_user.car_shopping)
 
  #list_products/add_to_list
  #mi_url_path
  #sin as: href="localhost:3000/list_products/add-to-list?product_id=1"
  #con as: add_to_list_path(product_id: @product.id)
  #to: controlador#metodo_del_controlador
  post "/add-to-list", to: "list_products#add_to_list", controller: "list_products", as: :add_to_list
  
  delete "/remove-from-cart/:id", to: "list_products#remove_from_cart", as: :remove_from_cart

  post "/shop_from_cart/", to: "list_products#shop_from_cart", as: :shop_from_cart
  
  
  #user_profile_path
  #link_to 'Mi perfil', 
  #views/users/profile.html.erb
  #get "/mi-perfil", to: "users#profile", controller: "users", as: :user_profile



  resources :editorials
  devise_for :users
  root to: "products#index"


  
  resources :carshoppings
  resources :whishlists
  resources :addres
  resources :shopingcars
  resources :whislists
  resources :products
  resources :categories
  resources :roles

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id           :bigint           not null, primary key
#  description  :text
#  name         :string
#  price        :integer
#  stock        :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  category_id  :bigint           not null
#  editorial_id :bigint           not null
#
# Indexes
#
#  index_products_on_category_id   (category_id)
#  index_products_on_editorial_id  (editorial_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (editorial_id => editorials.id)
#
class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :img
  belongs_to :editorial

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :find_or_create_cart, only: %i[ index show create ]
  
  # GET /products or /products.json
  def index
    @products = Product.all
    @categories = Category.all
    @editorials = Editorial.all
  end

  # GET /products/1 or /products/1.json
  def show
  end
 
  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_path, status: :see_other, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :stock, :description, :category_id, :img, :editorial_id)
    end


    def find_or_create_cart
      if user_signed_in? 
        @carshopping = Carshopping.find_or_create_by(user_id: current_user.id)
      end
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true, enctype: "multipart/form-data") do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :category_id, "Category" %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :editorial %>
    <%= form.collection_select :editorial_id, Editorial.all, :id, :name, prompt: "Select an Editorial" %>
  </div>

  <div class="field">
    <%= form.label :img, "Image" %>
    <%= form.file_field :img %>  <!-- Este es el campo de la imagen -->
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Stock:</strong>
    <%= product.stock %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category_id %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<div id="products" style="display: flex; gap: 20px;">

  
  <div style="flex: 0 0 300px; display: flex; flex-direction: column; gap: 20px;">

  
    <div style="background-color: #f8f8f8; border: 1px solid #ddd; border-radius: 5px; padding: 15px;">
    <h4 style="font-size: 1.25rem; font-weight: bold;">Categorías</h4>
    <ul style="list-style-type: none; padding: 0;">
      <% @categories.each do |category| %>
        <li>
          <a href="<%= category_path(category) %>" style="color: #007bff; text-decoration: none;">
            <%= category.name %>
          </a>
        </li>
      <% end %>
    </ul>
  </div>

    <div style="background-color: #f8f8f8; border: 1px solid #ddd; border-radius: 5px; padding: 15px;">
      <h4 style="font-size: 1.25rem; font-weight: bold;">Editorial</h4>
      <% @editorials.each do |editorial| %>
        <li>
          <a href="<%= editorial_path(editorial) %>" style="color: #007bff; text-decoration: none;">
            <%= editorial.name %>
          </a>
        </li>
      <% end %>
      </ul>
    </div>

  </div>


  <div class="container" style="flex: 1; display: flex; flex-wrap: wrap; gap: 20px;">
    <% @products.each do |product| %>
      
      
      
        <div style="background-color: white; border: 1px solid #ddd; border-radius: 5px; overflow: hidden; box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);">
          <% if product.img.attached? %>
            <%= image_tag url_for(product.img), alt: "Image for #{product.name}", style: "width: 100%; height: 300px; object-fit: cover;" %>
          <% else %>
            <img src="default_image_url.jpg" style="width: 100%; height: 200px; object-fit: cover;" alt="Default image for #{product.name}">
          <% end %>

          <div style="padding: 15px;">
            <h5 style="font-size: 1.125rem; font-weight: bold; margin-bottom: 10px;"><%= product.name %></h5>
           
            <%= button_to "Agregar al Carrito", add_to_list_path(list_product: { product_id: product.id }), method: :post, class: 'btn btn-primary', style: 'display: inline-block; margin-top: 10px; background-color: blue; color: white; text-decoration: none; padding: 10px 15px; border-radius: 5px;' %>
          </div>
        </div>
       
      
    <% end %>
  </div>

</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>


<%= render @product %>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>

<% if @product.img.attached? %>
  <%= image_tag url_for(@product.img) %>
<% else %>
  <p>No image available</p>
<% end %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>