config/routes.rb
Rails.application.routes.draw do


  # GET -> list_products_path -> list_products_controller#index 
  # GET -> list_product_path -> list_products_controller#show -> :id
  # POST -> create_list_product_path -> list_products_controller#create -> product_id
  resources :list_products
  #add_to_list -> Post -> cree un nuevo ListProduct(user: current_user, product: product, carshopping: current_user.car_shopping)
 
  #list_products/add_to_list
  #mi_url_path
  #sin as: href="localhost:3000/list_products/add-to-list?product_id=1"
  #con as: add_to_list_path(product_id: @product.id)
  #to: controlador#metodo_del_controlador
  post "/add-to-list", to: "list_products#add_to_list", controller: "list_products", as: :add_to_list
  
  delete "/remove-from-cart/:id", to: "list_products#remove_from_cart", as: :remove_from_cart

  post "/shop_from_cart/", to: "list_products#shop_from_cart", as: :shop_from_cart
  
  
  #user_profile_path
  #link_to 'Mi perfil', 
  #views/users/profile.html.erb
  #get "/mi-perfil", to: "users#profile", controller: "users", as: :user_profile



  resources :editorials
  devise_for :users
  root to: "products#index"


  
  resources :carshoppings
  resources :whishlists
  resources :addres
  resources :shopingcars
  resources :whislists
  resources :products
  resources :categories
  resources :roles

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/editorial.rb
# == Schema Information
#
# Table name: editorials
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Editorial < ApplicationRecord
    has_many :products
end

app/controllers/editorials_controller.rb
class EditorialsController < ApplicationController
  before_action :set_editorial, only: %i[ show edit update destroy ]

  # GET /editorials or /editorials.json
  def index
    @editorials = Editorial.all
  end

  # GET /editorials/1 or /editorials/1.json
  def show
  end

  # GET /editorials/new
  def new
    @editorial = Editorial.new
  end

  # GET /editorials/1/edit
  def edit
  end

  # POST /editorials or /editorials.json
  def create
    @editorial = Editorial.new(editorial_params)

    respond_to do |format|
      if @editorial.save
        format.html { redirect_to @editorial, notice: "Editorial was successfully created." }
        format.json { render :show, status: :created, location: @editorial }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @editorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editorials/1 or /editorials/1.json
  def update
    respond_to do |format|
      if @editorial.update(editorial_params)
        format.html { redirect_to @editorial, notice: "Editorial was successfully updated." }
        format.json { render :show, status: :ok, location: @editorial }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @editorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editorials/1 or /editorials/1.json
  def destroy
    @editorial.destroy!

    respond_to do |format|
      format.html { redirect_to editorials_path, status: :see_other, notice: "Editorial was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_editorial
      @editorial = Editorial.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def editorial_params
      params.require(:editorial).permit(:name)
    end
end

app/helpers/editorials_helper.rb
module EditorialsHelper
end

app/views/editorials/_editorial.html.erb
<div id="<%= dom_id editorial %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= editorial.name %>
  </p>

</div>

app/views/editorials/_form.html.erb
<%= form_with(model: editorial, class: "contents") do |form| %>
  <% if editorial.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(editorial.errors.count, "error") %> prohibited this editorial from being saved:</h2>

      <ul>
        <% editorial.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-400 outline-none focus:outline-blue-600 px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/editorials/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing editorial</h1>

  <%= render "form", editorial: @editorial %>

  <%= link_to "Show this editorial", @editorial, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to editorials", editorials_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/editorials/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Editorials" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Editorials</h1>
    <%= link_to "New editorial", new_editorial_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="editorials" class="min-w-full">
    <% @editorials.each do |editorial| %>
      <%= render editorial %>
      <p>
        <%= link_to "Show this editorial", editorial, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/editorials/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New editorial</h1>

  <%= render "form", editorial: @editorial %>

  <%= link_to "Back to editorials", editorials_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/editorials/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @editorial %>

    <%= link_to "Edit this editorial", edit_editorial_path(@editorial), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to editorials", editorials_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this editorial", @editorial, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>